# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."pinchflat-pinchflat" = {
    image = "ghcr.io/kieraneglin/pinchflat:latest";
    environment = {
      "TZ" = "America/New_York";
    };
    volumes = [
      "/host/path/to/config:/config:rw"
      "/host/path/to/downloads:/downloads:rw"
    ];
    ports = [
      "8945:8945/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=pinchflat"
      "--network=pinchflat_default"
    ];
  };
  systemd.services."docker-pinchflat-pinchflat" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-pinchflat_default.service"
    ];
    requires = [
      "docker-network-pinchflat_default.service"
    ];
    partOf = [
      "docker-compose-pinchflat-root.target"
    ];
    wantedBy = [
      "docker-compose-pinchflat-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-pinchflat_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f pinchflat_default";
    };
    script = ''
      docker network inspect pinchflat_default || docker network create pinchflat_default
    '';
    partOf = [ "docker-compose-pinchflat-root.target" ];
    wantedBy = [ "docker-compose-pinchflat-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-pinchflat-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
