# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."readarr" = {
    image = "readarr-custom:latest";
    environment = {
      "PUID" = "1009";
      "PGID" = "169";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/srv/data1tb/.config/readarr:/config:rw"
      "/srv/data1tb/data:/data:rw"
    ];
    ports = [
      "8787:8787/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
}
