# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  networking.firewall.allowedTCPPorts = [8888];
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."unmanic" = {
    image = "josh5/unmanic:latest";
    pull = "always";

    environment = {
      "PGID" = "169";
      "PUID" = "1121";
    };
    volumes = [
      "/srv/data1tb/.config/unmanic:/config:rw"
      "/srv/data1tb/data/library:/library:rw"
      "/srv/data1tb/data/tmp/unmanic:/tmp/unmanic:rw"
    ];
    ports = [
      "8888:8888/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=unmanic"
      "--network=unmanic_default"
    ];
  };
  systemd.services."docker-unmanic" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-unmanic_default.service"
    ];
    requires = [
      "docker-network-unmanic_default.service"
    ];
    partOf = [
      "docker-compose-unmanic-root.target"
    ];
    wantedBy = [
      "docker-compose-unmanic-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-unmanic_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f unmanic_default";
    };
    script = ''
      docker network inspect unmanic_default || docker network create unmanic_default
    '';
    partOf = [ "docker-compose-unmanic-root.target" ];
    wantedBy = [ "docker-compose-unmanic-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-unmanic-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
