{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  virtualisation.oci-containers.containers.wud = {
    image = "getwud/wud:latest";

    ports = [
      "3000:3000"
    ];

    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock"
    ];

    environment = {
      WUD_WATCHER_LOCAL_DOCKER = "true";
      WUD_WATCHER_LOCAL_SOCKET = "/var/run/docker.sock";
    };

    extraOptions = [
      "--name=wud"
    ];
  };

  systemd.services."docker-wud" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wud_default.service"
    ];
    requires = [
      "docker-network-wud_default.service"
    ];
    partOf = [
      "docker-compose-wud-root.target"
    ];
    wantedBy = [
      "docker-compose-wud-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-wud_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f wud_default";
    };
    script = ''
      docker network inspect wud_default || docker network create wud_default
    '';
    partOf = [ "docker-compose-wud-root.target" ];
    wantedBy = [ "docker-compose-wud-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-wud-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}