# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."audiobookrequest" = {
    image = "markbeep/audiobookrequest:1";
    environment = {
      "PGID" = "169";
      "PUID" = "1110";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/srv/data1tb/.config/audiobookrequest:/config:rw"
      "/srv/data1tb/data:/data:rw"
    ];
    ports = [
      "8000:8000/tcp"
    ];
  };
}
