# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."audiobookrequest" = {
    image = "markbeep/audiobookrequest:1";
    environment = {
      "PGID" = "169";
      "PUID" = "1010";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/srv/data1tb/.config/audiobookrequest:/config:rw"
      "/srv/data1tb/data:/data:rw"
    ];
    ports = [
      "8000:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bookshelf"
      "--network=audiobookrequest_default"
    ];
  };
  systemd.services."docker-audiobookrequest" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-audiobookrequest_default.service"
    ];
    requires = [
      "docker-network-audiobookrequest_default.service"
    ];
    partOf = [
      "docker-compose-audiobookrequest-root.target"
    ];
    wantedBy = [
      "docker-compose-audiobookrequest-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-audiobookrequest_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f audiobookrequest_default";
    };
    script = ''
      docker network inspect audiobookrequest_default || docker network create audiobookrequest_default
    '';
    partOf = [ "docker-compose-audiobookrequest-root.target" ];
    wantedBy = [ "docker-compose-audiobookrequest-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-audiobookrequest-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
