# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."bazarr" = {
    image = "lscr.io/linuxserver/bazarr:latest";
    environment = {
      "PGID" = "169";
      "PUID" = "1117";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/srv/data1tb/.config/bazarr:/config:rw"
      "/srv/data1tb/data/library/movies:/movies:rw"
      "/srv/data1tb/data/library/shows:/shows:rw"
    ];
    ports = [
      "6767:6767/tcp"
    ];
  }
}
