# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyseerr" = {
    image = "ghcr.io/fallenbagel/jellyseerr:latest";
    environment = {
      "LOG_LEVEL" = "debug";
      "PORT" = "5055";
      "TZ" = "Asia/Tashkent";
    };
    volumes = [
      "/srv/data1tb/.config/jellyseer:/app/config:rw"
    ];
    ports = [
      "5055:5055/tcp"
    ];
  }
}
