# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyseerr" = {
    image = "ghcr.io/fallenbagel/jellyseerr:latest";
    environment = {
      "LOG_LEVEL" = "debug";
      "PORT" = "5055";
      "TZ" = "Asia/Tashkent";
    };
    volumes = [
      "/srv/data1tb/.config/jellyseer:/app/config:rw"
    ];
    ports = [
      "5055:5055/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1"
      "--health-interval=15s"
      "--health-retries=3"
      "--health-start-period=20s"
      "--health-timeout=3s"
      "--network-alias=jellyseerr"
      "--network=jellyseer_default"
    ];
  };
  systemd.services."docker-jellyseerr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-jellyseer_default.service"
    ];
    requires = [
      "docker-network-jellyseer_default.service"
    ];
    partOf = [
      "docker-compose-jellyseer-root.target"
    ];
    wantedBy = [
      "docker-compose-jellyseer-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-jellyseer_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f jellyseer_default";
    };
    script = ''
      docker network inspect jellyseer_default || docker network create jellyseer_default
    '';
    partOf = [ "docker-compose-jellyseer-root.target" ];
    wantedBy = [ "docker-compose-jellyseer-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyseer-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
