# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."lazylibrarian" = {
    image = "lscr.io/linuxserver/lazylibrarian:latest";
    environment = {
      "DOCKER_MODS" = "linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg";
      "PGID" = "169";
      "PUID" = "1005";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/srv/data1tb/data/library/books/:/books:rw"
      "/srv/data1tb/data/usenet/books/:/downloads:rw"
      "/srv/data1tb/lazylibrarian/:/config:rw"
    ];
    ports = [
      "5299:5299/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=lazylibrarian"
      "--network=lazylibrarian_default"
    ];
  };
  systemd.services."docker-lazylibrarian" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-lazylibrarian_default.service"
    ];
    requires = [
      "docker-network-lazylibrarian_default.service"
    ];
    partOf = [
      "docker-compose-lazylibrarian-root.target"
    ];
    wantedBy = [
      "docker-compose-lazylibrarian-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-lazylibrarian_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f lazylibrarian_default";
    };
    script = ''
      docker network inspect lazylibrarian_default || docker network create lazylibrarian_default
    '';
    partOf = [ "docker-compose-lazylibrarian-root.target" ];
    wantedBy = [ "docker-compose-lazylibrarian-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-lazylibrarian-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
