# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."lidarr" = {
    image = "lscr.io/linuxserver/lidarr:latest";
    environment = {
      "DOCKER_MODS" = "linuxserver/mods:lidarr-flac2mp3";
      "PGID" = "169";
      "PUID" = "1109";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/srv/data1tb/.config/lidarr:/config:rw"
      "/srv/data1tb/data:/data:rw"
    ];
    ports = [
      "8686:8686/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=lidarr"
      "--network=lidarr_default"
    ];
  };
  systemd.services."docker-lidarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-lidarr_default.service"
    ];
    requires = [
      "docker-network-lidarr_default.service"
    ];
    partOf = [
      "docker-compose-lidarr-root.target"
    ];
    wantedBy = [
      "docker-compose-lidarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-lidarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f lidarr_default";
    };
    script = ''
      docker network inspect lidarr_default || docker network create lidarr_default
    '';
    partOf = [ "docker-compose-lidarr-root.target" ];
    wantedBy = [ "docker-compose-lidarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-lidarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
