# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."radarr" = {
    image = "lscr.io/linuxserver/radarr:latest";
    environment = {
      "DOCKER_MODS" = "linuxserver/mods:radarr-striptracks";
      "PGID" = "169";
      "PUID" = "1108";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/srv/data1tb/.config/radarr:/config:rw"
      "/srv/data1tb/data:/data:rw"
    ];
    ports = [
      "7878:7878/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=radarr"
      "--network=radarr_default"
    ];
  };
  systemd.services."docker-radarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-radarr_default.service"
    ];
    requires = [
      "docker-network-radarr_default.service"
    ];
    partOf = [
      "docker-compose-radarr-root.target"
    ];
    wantedBy = [
      "docker-compose-radarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-radarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f radarr_default";
    };
    script = ''
      docker network inspect radarr_default || docker network create radarr_default
    '';
    partOf = [ "docker-compose-radarr-root.target" ];
    wantedBy = [ "docker-compose-radarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-radarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
