# Auto-generated using compose2nix v0.3.3-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."bazarr" = {
    image = "lscr.io/linuxserver/bazarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1003";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/srv/data1tb/bazarr/config:/config:rw"
      "/srv/data1tb/data:/data:rw"
    ];
    ports = [
      "6767:6767/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bazarr"
      "--network=bazarr_default"
    ];
  };
  systemd.services."docker-bazarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bazarr_default.service"
      "docker.service"
    ];
    requires = [
      "docker-network-bazarr_default.service"
      "docker.service"
    ];
    partOf = [
      "docker-compose-bazarr-root.target"
    ];
    wantedBy = [
      "docker-compose-bazarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-bazarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f bazarr_default";
    };
    script = ''
      docker network inspect bazarr_default || docker network create bazarr_default
    '';
    partOf = [ "docker-compose-bazarr-root.target" ];
    wantedBy = [ "docker-compose-bazarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-bazarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
