# Auto-generated using compose2nix v0.3.3-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."mediathekarr" = {
    image = "pcjones/mediathekarr:beta";
    environment = {
      "MEDIATHEKARR_API_BASE_URL" = "https://mediathekarr.pcjones.de/api/v1";
      "PGID" = "169";
      "PUID" = "1003";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/srv/data1tb/data/usenet/:/data/usenet:rw"
      "/srv/data1tb/mediathekarr:/data/mediathek/incomplete:rw"
      "/srv/data1tb/mediathekarr/config:/app/config:rw"
    ];
    ports = [
      "0.0.0.0:5007:5007/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      # Add DNS server to resolve .tails domains
      "--network=host"
    ];
  };
  systemd.services."docker-mediathekarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker.service"
    ];
    requires = [
      "docker.service"
    ];
    partOf = [
      "docker-compose-mediathekarr-root.target"
    ];
    wantedBy = [
      "docker-compose-mediathekarr-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-mediathekarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
