# Auto-generated using compose2nix v0.3.3-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."sabnzbd" = {
    image = "lscr.io/linuxserver/sabnzbd:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1004";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/srv/data1tb/data/usenet:/data/usenet:rw"
      "/srv/data1tb/sabnzbd/config:/config:rw"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sabnzbd"
      "--network=sabnzbd_default"
    ];
  };
  systemd.services."docker-sabnzbd" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sabnzbd_default.service"
    ];
    requires = [
      "docker-network-sabnzbd_default.service"
    ];
    partOf = [
      "docker-compose-sabnzbd-root.target"
    ];
    wantedBy = [
      "docker-compose-sabnzbd-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-sabnzbd_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f sabnzbd_default";
    };
    script = ''
      docker network inspect sabnzbd_default || docker network create sabnzbd_default
    '';
    partOf = [ "docker-compose-sabnzbd-root.target" ];
    wantedBy = [ "docker-compose-sabnzbd-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-sabnzbd-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
